[package]
name = "week11-URLShortener"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0"
rand = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
